version: '3'

services:
  db:
    image: "hubmap/cross-modality-query-db:latest"
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:
      - ../../data/postgres:/var/lib/postgresql/data
  mongo:
    image: mongo:latest
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=rootpassword
      - MONGO_INITDB_DATABASE=token_store
    volumes:
      - ../../data/mongo:/data/db
    command:
      - mongod
  memcached:
    image: memcached:latest
  redis:
    image: redis:latest
    restart: "${DOCKER_RESTART_POLICY:-unless-stopped}"
    stop_grace_period: "${DOCKER_STOP_GRACE_PERIOD:-3s}"
    volumes:
      - ../../data/redis:/data
  web:
    image: "hubmap/cross-modality-query-dev:latest"
    command: /code/wait-for-it.sh --timeout=0 db:5432 -- python3 /code/manage.py runserver 0.0.0.0:8000
    volumes:
      - ../../hubmap:/code
    ports:
      - "8000:8000"
    depends_on:
      - db
      - mongo
  worker:
    image: "hubmap/cross-modality-query-dev:latest"
    command: /code/wait-for-it.sh --timeout=0 db:5432 -- celery -A hubmap_query worker
    volumes:
      - ../../hubmap:/code
    depends_on:
      - db
      - redis
      - mongo
