version: '3'

services:
  db:
    image: postgres:13
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:
      - ../../data/postgres:/var/lib/postgresql/data
  memcached:
    image: memcached:latest
  web:
    image: "hubmap/cross-modality-query-dev:latest"
    command: python3 /code/manage.py runserver 0.0.0.0:8000
    volumes:
      - ../../hubmap:/code
    ports:
      - "8000:8000"
    depends_on:
      - db
