version: '3'

services:
  db:
    image: "hubmap/cross-modality-query-db:latest"
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - "5432:5432"
    volumes:
      -  /data/postgres:/var/lib/postgresql/data
  memcached:
    image: memcached:latest
  uwsgi:
    image: "hubmap/cross-modality-query-prod:latest"
    ports:
      - "5000:5000"
    expose:
      - 5000
    volumes:
      - /opt/secret:/opt/secret
  redis:
    image: redis:latest
    restart: "${DOCKER_RESTART_POLICY:-unless-stopped}"
    stop_grace_period: "${DOCKER_STOP_GRACE_PERIOD:-3s}"
    volumes:
      - ../../data/redis:/data
  worker:
    image: "hubmap/cross-modality-query-dev:latest"
    command: /code/wait-for-it.sh --timeout=0 db:5432 -- celery -A hubmap_query worker
    volumes:
      - ../../hubmap:/code
    depends_on:
      - db
      - redis
