# Generated by Django 3.1.3 on 2020-11-24 19:28

import django.contrib.postgres.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Cell",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("cell_id", models.CharField(db_index=True, max_length=64, null=True)),
                ("protein_mean", models.JSONField(blank=True, db_index=True, null=True)),
                ("protein_total", models.JSONField(blank=True, db_index=True, null=True)),
                ("protein_covar", models.JSONField(blank=True, db_index=True, null=True)),
                (
                    "cell_shape",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.FloatField(),
                        blank=True,
                        db_index=True,
                        null=True,
                        size=None,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="CellGrouping",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("grouping_name", models.CharField(max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name="Dataset",
            fields=[
                (
                    "cellgrouping_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="query_app.cellgrouping",
                    ),
                ),
                ("uuid", models.CharField(max_length=32)),
                (
                    "modality",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="datasets",
                        to="query_app.modality",
                    ),
                ),
            ],
            bases=("query_app.cellgrouping",),
        ),
        migrations.CreateModel(
            name="Modality",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("modality_name", models.CharField(max_length=16)),
            ],
        ),
        migrations.CreateModel(
            name="Organ",
            fields=[
                (
                    "cellgrouping_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="query_app.cellgrouping",
                    ),
                ),
            ],
            bases=("query_app.cellgrouping",),
        ),
    ]
