# Generated by Django 3.2 on 2021-05-03 18:06

from django.contrib.postgres.operations import TrigramExtension
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("query_app", "0003_statreport"),
    ]

    operations = [TrigramExtension()]
