# Generated by Django 3.2 on 2021-05-03 18:06

import django.db.models.deletion
from django.contrib.postgres.operations import TrigramExtension
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("query_app", "0004_trigram"),
    ]

    operations = [
        migrations.CreateModel(
            name="PrecomputedPercentage",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "modality",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="query_app.modality",
                    ),
                ),
                (
                    "dataset",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="query_app.dataset",
                    ),
                ),
                ("var_id", models.CharField(null=True, max_length=64, db_index=True)),
                ("cutoff", models.FloatField(null=True, db_index=True)),
                ("percentage", models.FloatField(null=True, db_index=True)),
                ("num_cells_excluded", models.IntegerField(null=True, db_index=True)),
            ],
        ),
    ]
