# Generated by Django 4.0.3 on 2022-04-05 01:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("query_app", "0005_auto_20211116_1540"),
    ]

    operations = [
        migrations.CreateModel(
            name="CellType",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("grouping_name", models.CharField(max_length=64, null=True)),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.AddField(
            model_name="cell",
            name="cell_type",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="cells",
                to="query_app.celltype",
            ),
        ),
    ]
