# Generated by Django 3.1.1 on 2020-09-09 19:24

import django.contrib.postgres.fields
import django.contrib.postgres.fields.jsonb
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ATAC_Quant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cell_id', models.CharField(db_index=True, max_length=60)),
                ('gene_id', models.CharField(db_index=True, max_length=20)),
                ('value', models.FloatField(db_index=True)),
            ],
        ),
        migrations.CreateModel(
            name='Cell',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cell_id', models.CharField(db_index=True, max_length=60)),
                ('modality', models.CharField(db_index=True, max_length=20)),
                ('protein_mean', django.contrib.postgres.fields.jsonb.JSONField(db_index=True)),
                ('protein_total', django.contrib.postgres.fields.jsonb.JSONField(db_index=True)),
                ('protein_covar', django.contrib.postgres.fields.jsonb.JSONField(db_index=True)),
                ('cell_shape', django.contrib.postgres.fields.ArrayField(base_field=models.FloatField(), db_index=True, size=None)),
            ],
        ),
        migrations.CreateModel(
            name='Gene',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gene_symbol', models.CharField(db_index=True, max_length=20)),
                ('go_terms', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=50), db_index=True, size=None)),
            ],
        ),
        migrations.CreateModel(
            name='RNA_Quant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cell_id', models.CharField(db_index=True, max_length=60)),
                ('gene_id', models.CharField(db_index=True, max_length=20)),
                ('value', models.FloatField(db_index=True)),
            ],
        ),
        migrations.CreateModel(
            name='Cell_Grouping',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group_type', models.CharField(db_index=True, max_length=20)),
                ('group_id', models.CharField(db_index=True, max_length=20)),
                ('cells', models.ManyToManyField(related_name='groupings', to='query_app.Cell')),
                ('genes', models.ManyToManyField(related_name='groups', to='query_app.Gene')),
                ('marker_genes', models.ManyToManyField(related_name='marker_groups', to='query_app.Gene')),
            ],
        ),
    ]
