# Generated by Django 2.2 on 2019-06-25 15:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='DataType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='Gene',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gene_symbol', models.CharField(max_length=20, db_index=True)),
                ('go_terms', ArrayField(db_index=True))
            ],
        ),
        migrations.CreateModel(
            name='Cell',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cell_id', models.CharField(db_index=True, max_length=60))
                ('modality', models.CharField(db_index=True, max_length=20))
                ('protein_mean', JSONField(db_index=True))
                ('protein_total', JSONField(db_index=True))
                ('protein_covar', JSONField(db_index=True))
                ('cell_shape', ArrayField(db_index=True))
                ('groupings', models.ManyToManyField(Cell_Grouping))
            ],
        ),
        migrations.CreateModel(
            name='Cell_Grouping',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group_type', models.CharField(db_index=True, max_length=20))
                ('group_id', models.CharField(db_index=True, max_length=20))
            #   ('cells', models.ManyToManyField(Cell))
                ('genes', models.ManyToManyField(Gene))
                ('marker_genes', models.ManyToManyField(Gene))
            ],
        ),
        migrations.CreateModel(
            name='RNA_Quant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cell_id', models.CharField(db_index=True, max_length=60))
                ('gene_id', models.CharField(db_index=True, max_length=20))
                ('value', models.FloatField(db_index=True))
            ],
        ),
        migrations.CreateModel(
            name='ATAC_Quant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cell_id', models.CharField(db_index=True, max_length=60))
                ('gene_id', models.CharField(db_index=True, max_length=20))
                ('value', models.FloatField(db_index=True))
            ],
        ),
    ]
